name: MagicChest
version: 1.2.8
description: Summons little gremlins to organize your chests when you're not looking.
authors: [zonedabone, uvbeenzaned]
main: org.zonedabone.magicchest.MagicChest
softdepend: [dtlTraders, ChestCommands, FastCraft, AShops, SkillAPI, SimpleGUI Creator]
dev-url: http://dev.bukkit.org/server-mods/magicchest/
commands:
  magicchest:
    description: Master MagicChest command.
    aliases: mgcs
    permission: magicchest.sort
    usage: |
      Type /<command> help - to show this usage help.
      Type /<command> on/off - to enable or disable auto inventory sorting.
      Type /<command> invon/invoff - to enable or disable auto item pickup player inventory sorting.
      Type /<command> reload - to reload MagicChest's config file. (for ops and those who have permissions)
permissions:
    magicchest.sort:
        description: Sorts all inventories that this player opens.
        children:
            magicchest.help: true
            magicchest.sort.chest: true
            magicchest.sort.dispenser: true
            magicchest.sort.dropper: true
            magicchest.sort.enderchest: true
            magicchest.sort.hopper: true
            magicchest.sort.inventory: true
    magicchest.help:
        description: Shows MagicChest usage help.
    magicchest.sort.chest:
        description: Sorts chests that this player opens.
    magicchest.sort.dispenser:
        description: Sorts dispensers that this player opens.
    magicchest.sort.dropper:
        description: Sorts droppers that this player opens.
    magicchest.sort.enderchest:
        description: Sorts ender chests that this player opens.
    magicchest.sort.hopper:
        description: Sorts hoppers that this player opens.
    magicchest.reload:
        description: Reloads all of MagicChest's config.